name: Release Drafter

on:
  push:
    branches: [latest]
  pull_request: # required for autolabeler
    branches: [latest]
    types: [opened, reopened, synchronize, ready_for_review, review_requested]
  workflow_dispatch:

jobs:
  stale:
    uses: homebridge/.github/.github/workflows/release-drafter.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}